global:
  scrape_interval:     5s
  evaluation_interval: 15s
  external_labels:
    monitor: 'Prometheus-Monitor'
  
scrape_configs:
  - job_name: 'cadvisor'
    dns_sd_configs:
    - names:
      - 'tasks.cadvisor'
      type: 'A'
      port: 8080

  - job_name: 'node-exporter'
    dns_sd_configs:
    - names:
      - 'tasks.node-exporter'
      type: 'A'
      port: 9100



